import {sliceGraph,searchNodes,neighbors,layoutGraph,layoutOverview,overviewRegions} from './graph.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const types={affiliation:'소속·역할',partnership:'협력·투자',history:'과거 이력',competition:'사업 경쟁 · 해석'};
let data,byId,sectors,current,positions;
const state={sector:'all',relation:'all',view:'map',selected:null,edge:null,zoom:1,x:0,y:0};
const initials=n=>n.kind==='organization'?n.en.replace(/[^a-zA-Z]/g,'').slice(0,2).toUpperCase():(n.en||n.name).split(/\s+/).slice(0,2).map(s=>s[0]).join('').toUpperCase();
const sourceLinks=e=>e.sources.map(s=>`<a class="source-link" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a>`).join('');
function updateHash(){const p=new URLSearchParams({sector:state.sector,view:state.view,relation:state.relation});if(state.selected)p.set('node',state.selected);history.replaceState(null,'','#'+p);}
function readHash(){const p=new URLSearchParams(location.hash.slice(1));if(['all',...data.sectors.map(s=>s.id)].includes(p.get('sector')))state.sector=p.get('sector');if(['map','directory','sources','feed'].includes(p.get('view')))state.view=p.get('view');if(['all',...Object.keys(types)].includes(p.get('relation')))state.relation=p.get('relation');state.selected=byId.has(p.get('node'))?p.get('node'):null;}
function setView(view){state.view=view;$$('.view').forEach(e=>e.hidden=e.id!==view+'-view');$$('.nav-item').forEach(e=>e.classList.toggle('active',e.dataset.view===view));$('#view-title').textContent={map:'관계 탐색',directory:'계정 디렉터리',sources:'근거 라이브러리',feed:'발언 모아보기'}[view];updateHash();}
function focusNode(id){state.selected=id;state.edge=null;if(!current.nodes.some(n=>n.id===id)){state.sector=byId.get(id).sector;state.relation='all';}$('#search').value='';$('#search-results').hidden=true;setView('map');render();}
function drawGraph(){
 const relevant=neighbors(current.edges,state.selected);for(const id of [...relevant])for(const neighbor of neighbors(current.edges,id))relevant.add(neighbor);relevant.add(state.selected);
 const center=positions.get(state.selected);let markup='<g id="graph-transform">';
 if(state.sector==='all')for(const r of overviewRegions){const sector=sectors.get(r.id),count=current.nodes.filter(n=>n.sector===r.id).length;markup+=`<g class="sector-region" style="--region-color:${sector.color}" pointer-events="none"><rect x="${r.x}" y="${r.y}" width="${r.width}" height="${r.height}" rx="20"/><text x="${r.x+24}" y="${r.y+35}">${esc(sector.name)}<tspan class="region-count"> / ${count} 노드</tspan></text></g>`;}
 for(const e of current.edges){const a=positions.get(e.from),b=positions.get(e.to),focus=e.from===state.selected||e.to===state.selected;const path=`M${a.x},${a.y} L${b.x},${b.y}`;markup+=`<g class="edge-group" data-edge="${e.id}" role="button" tabindex="0" aria-label="${esc(byId.get(e.from).name+' → '+byId.get(e.to).name+' · '+e.label)}"><title>${esc(e.label)}</title><path class="edge ${e.type} ${focus?'focused':center?'dim':''}" d="${path}"/><path class="edge-hit" d="${path}"/>${focus?`<text class="edge-label" x="${(a.x+b.x)/2}" y="${(a.y+b.y)/2-5}" text-anchor="middle">${esc(e.label)}</text>`:''}</g>`;}
 for(const n of current.nodes){const p=positions.get(n.id),selected=n.id===state.selected,color=sectors.get(n.sector).color;markup+=`<g class="node ${selected?'selected':''} ${center&&!relevant.has(n.id)?'dim':''}" style="--node-color:${color}" data-node="${n.id}" transform="translate(${p.x},${p.y})" role="button" tabindex="0" aria-label="${esc(n.name+' · '+n.role)}"><title>${esc(n.name+' · '+n.role)}</title><circle class="node-halo" r="${selected?40:32}"/>${n.kind==='organization'?'<rect class="node-body" x="-23" y="-23" width="46" height="46" rx="11"/>':'<circle class="node-body" r="23"/>'}<text class="node-initial" text-anchor="middle" y="5">${esc(initials(n))}</text><text class="node-label" text-anchor="middle" y="45">${esc(n.name)}</text><text class="node-subtitle" text-anchor="middle" y="60">${esc(n.kind==='person'?n.en:sectors.get(n.sector).name)}</text></g>`;}
 markup+='</g>';$('#network').innerHTML=markup;
 $$('[data-node]').forEach(el=>{el.addEventListener('click',()=>focusNode(el.dataset.node));el.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();focusNode(el.dataset.node);}});});
 $$('.edge-group').forEach(el=>{const action=()=>{state.edge=el.dataset.edge;renderEdge();};el.addEventListener('click',action);el.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();action();}});});
 $('#empty-graph').hidden=current.edges.length>0;transform();
}
function transform(){const [cx,cy]=state.sector==='all'?[900,590]:[500,330];const g=$('#graph-transform');if(g)g.setAttribute('transform',`translate(${cx+state.x} ${cy+state.y}) scale(${state.zoom}) translate(${-cx} ${-cy})`);$('#zoom-reset').textContent=Math.round(state.zoom*100)+'%';}
function renderDetail(){const n=byId.get(state.selected);if(!n){const linked=new Set(current.edges.flatMap(e=>[e.from,e.to]));$('#detail').innerHTML=`<div class="overview-summary"><div><span class="eyebrow">THE BIG PICTURE</span><h2>전체 관계를 한눈에</h2><p class="empty-note">${current.nodes.filter(n=>n.account).length}개 관심 계정과 ${current.nodes.filter(n=>!n.account).length}개 연결 노드, ${current.edges.length}개 관계입니다. 노드나 연결선을 선택하면 상세 근거를 볼 수 있습니다.</p></div><div><span class="tag neutral">분야별 배치 · 영향력 순위 아님</span><p class="empty-note">선이 없는 ${current.nodes.filter(n=>!linked.has(n.id)).length}개 노드는 현재 필터에서 확인된 연결이 없습니다. 배경 영역은 분야를 구분하며 소속 관계를 뜻하지 않습니다.</p></div></div>`;return;}
 const connections=data.edges.filter(e=>(e.from===n.id||e.to===n.id)&&(state.relation==='all'||e.type===state.relation));
 $('#detail').innerHTML=`<div class="detail-top">ENTITY PROFILE <span>${n.kind==='person'?'PERSON':'ORGANIZATION'}</span></div><div class="profile-block"><div class="profile-icon ${n.kind}">${esc(initials(n))}</div><h2>${esc(n.name)}</h2><span class="profile-en">${esc(n.en)}</span><p class="profile-role">${esc(n.role)}</p><div class="tags"><span class="tag">${esc(sectors.get(n.sector).name)}</span><span class="tag neutral">${n.account?'관심 계정':'연결 노드'}</span></div>${n.url?`<a class="profile-link" href="${esc(n.url)}" target="_blank" rel="noopener noreferrer">𝕏 @${esc(n.handle)} ↗</a>`:''}</div><div class="detail-section-title">연결된 관계 <span>${String(connections.length).padStart(2,'0')}</span></div>${connections.map(e=>{const other=byId.get(e.from===n.id?e.to:e.from);return `<button class="connection" data-detail-edge="${e.id}"><span class="connection-icon">${esc(initials(other))}</span><span class="connection-info"><strong>${esc(other.name)}</strong><small>${esc(e.label)}${e.status==='inference'?' · 해석':''}</small></span><span>↗</span></button>`;}).join('')||'<p class="empty-note">이 필터에서 확인된 관계가 없습니다. 근거를 확인한 연결부터 추가합니다.</p>'}<div class="detail-note"><strong>관계 확인 ${esc(n.checkedAt)}</strong><br>${esc(n.note||'공식 발표와 인물 프로필을 바탕으로 연결합니다.')}<br>선택한 노드의 연결 수는 영향력 점수가 아닙니다.</div>`;
 $$('[data-detail-edge]').forEach(el=>el.onclick=()=>{state.edge=el.dataset.detailEdge;renderEdge();});
}
function renderEdge(){const e=data.edges.find(e=>e.id===state.edge);if(!e)return renderDetail();const a=byId.get(e.from),b=byId.get(e.to);$('#detail').innerHTML=`<button class="back-button" id="back-profile">← 인물·기업 상세로</button><div class="detail-top">RELATIONSHIP <span>${e.status==='inference'?'INTERPRETATION':'SOURCE LINKED'}</span></div><div class="profile-block"><h2 class="relation-title">${esc(a.name)}<br><span style="color:#7e6d9b">↓</span><br>${esc(b.name)}</h2><p class="profile-role">${esc(e.label)}</p><span class="tag">${types[e.type]}</span></div><div class="detail-section-title">연결 근거 <span>${e.sources.length}</span></div>${sourceLinks(e)}<p class="empty-note">${esc(e.note||(e.type==='affiliation'?'공개 프로필에 명시된 역할 또는 창업 이력입니다. 현재 지휘 관계나 개인적인 친분을 뜻하지 않습니다.':'발표에 명시된 관계입니다. 세부 조건은 원문을 확인하세요.'))}</p><button class="profile-link" id="explore-target">${esc(b.name)} 중심으로 보기 →</button><div class="detail-note">${e.asOf?'발표일 '+e.asOf+'<br>':''}자료 확인 ${e.checkedAt}</div>`;$('#back-profile').onclick=()=>{state.edge=null;renderDetail();};$('#explore-target').onclick=()=>focusNode(b.id);}
function renderDirectory(){const list=searchNodes(data.nodes.filter(n=>n.account&&(state.sector==='all'||n.sector===state.sector)),$('#search').value);$('#directory-count').textContent=list.length+'개 계정';$('#directory').innerHTML=list.map(n=>`<button class="directory-item" data-directory-node="${n.id}"><span class="profile-icon ${n.kind}">${esc(initials(n))}</span><span><strong>${esc(n.name)}</strong><small>${esc(n.role)}</small><small class="handle">@${esc(n.handle)}</small></span></button>`).join('')||'<p class="empty-note">검색 조건에 맞는 계정이 없습니다.</p>';$$('[data-directory-node]').forEach(el=>el.onclick=()=>focusNode(el.dataset.directoryNode));}
function renderSources(){const q=$('#search').value.trim().toLowerCase();const edges=current.edges.filter(e=>!q||searchNodes([byId.get(e.from),byId.get(e.to)],q).length||e.label.toLowerCase().includes(q));$('#sources').innerHTML=edges.map(e=>`<article class="source-item"><span class="tag ${e.status==='inference'?'':'neutral'}">${types[e.type]}</span><h3>${esc(byId.get(e.from).name)} → ${esc(byId.get(e.to).name)}</h3><p>${esc(e.label)}${e.status==='inference'?' — 사업 영역에 따른 해석':''}</p>${sourceLinks(e)}<div class="source-date">${e.asOf?'발표 '+e.asOf+' · ':''}자료 확인 ${e.checkedAt}</div></article>`).join('')||'<p class="empty-note">현재 조건에 맞는 관계 자료가 없습니다.</p>';}
function render(){current=sliceGraph(data,state.sector,state.relation);if(!current.nodes.some(n=>n.id===state.selected))state.selected=state.sector==='all'?null:current.nodes.find(n=>n.account)?.id??null;const overview=state.sector==='all';positions=overview?layoutOverview(current.nodes):layoutGraph(current.nodes,current.edges);$('#map-view').classList.toggle('overview',overview);$('#network').setAttribute('viewBox',overview?'0 0 1800 1180':'0 0 1000 660');$('#sector').value=state.sector;$('#relation').value=state.relation;$$('.sector-button').forEach(el=>el.classList.toggle('selected',el.dataset.sector===state.sector));$('#overview-nav').classList.toggle('selected',overview);$('#graph-title').textContent=overview?'전체 인물·기업 관계도':sectors.get(state.sector).caption;$('#graph-caption').textContent=overview?'확대하거나 빈 공간을 드래그해 탐색하세요.':'연결을 선택하면 근거를 볼 수 있습니다.';$('#visible-count').textContent=current.nodes.length+' 노드 / '+current.edges.length+' 연결';drawGraph();renderDetail();renderDirectory();renderSources();updateHash();}
function showOverview(){Object.assign(state,{sector:'all',relation:'all',view:'map',selected:null,edge:null,zoom:1,x:0,y:0});$('#search').value='';$('#search-results').hidden=true;setView('map');render();}
function search(){renderDirectory();renderSources();const q=$('#search').value.trim();const list=q?searchNodes(data.nodes,q).slice(0,8):[];$('#search-results').hidden=!q||state.view==='directory'||state.view==='sources';$('#search-results').innerHTML=list.length?list.map(n=>`<button data-search-node="${n.id}">${esc(n.name)}<small>${esc(n.en)} · ${esc(n.role)}</small></button>`).join(''):'<p>검색 결과가 없습니다.</p>';$$('[data-search-node]').forEach(el=>el.onclick=()=>focusNode(el.dataset.searchNode));}
async function start(){const response=await fetch(new URL('./data.json',import.meta.url));if(!response.ok)throw new Error('관계 데이터를 불러오지 못했습니다.');data=await response.json();byId=new Map(data.nodes.map(n=>[n.id,n]));sectors=new Map(data.sectors.map(s=>[s.id,s]));readHash();$('#stat-accounts').textContent=data.nodes.filter(n=>n.account).length;$('#stat-edges').textContent=data.edges.length;$('#snapshot-date').textContent=data.updatedAt;$('#data-version').textContent='DATA v'+data.version+' · '+data.updatedAt;$('#sector').innerHTML='<option value="all">전체 분야</option>'+data.sectors.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');$('#sector-nav').innerHTML=data.sectors.map(s=>`<button class="sector-button" data-sector="${s.id}" style="--color:${s.color}"><i></i>${s.name}<span>${data.nodes.filter(n=>n.account&&n.sector===s.id).length}</span></button>`).join('');
 $$('[data-view]').forEach(el=>el.onclick=()=>{setView(el.dataset.view);search();});$$('[data-sector]').forEach(el=>el.onclick=()=>{state.sector=el.dataset.sector;state.edge=null;state.zoom=1;state.x=state.y=0;setView('map');render();});$('#sector').onchange=e=>{state.sector=e.target.value;state.edge=null;state.zoom=1;state.x=state.y=0;render();};$('#relation').onchange=e=>{state.relation=e.target.value;state.edge=null;render();};$('#search').oninput=search;$('#search').onkeydown=e=>{if(e.key==='Escape')$('#search-results').hidden=true;if(e.key==='Enter'&&!$('#search-results').hidden)$('#search-results button')?.click();};document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))$('#search-results').hidden=true;});document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('#search').focus();}});
 $('#reset').onclick=showOverview;$('#show-overview').onclick=showOverview;$('#overview-nav').onclick=showOverview;$('#zoom-in').onclick=()=>{state.zoom=Math.min(4,state.zoom+.25);transform();};$('#zoom-out').onclick=()=>{state.zoom=Math.max(.5,state.zoom-.25);transform();};$('#zoom-reset').onclick=()=>{state.zoom=1;state.x=state.y=0;transform();};
 let drag=null;$('#network').addEventListener('pointerdown',e=>{if(e.target.closest('.node,.edge-group'))return;drag={x:e.clientX,y:e.clientY,ox:state.x,oy:state.y};$('#network').setPointerCapture(e.pointerId);});$('#network').addEventListener('pointermove',e=>{if(!drag)return;const rect=$('#network').getBoundingClientRect(),vb=$('#network').viewBox.baseVal;const scale=Math.max(vb.width/rect.width,vb.height/rect.height);state.x=drag.ox+(e.clientX-drag.x)*scale;state.y=drag.oy+(e.clientY-drag.y)*scale;transform();});$('#network').addEventListener('pointerup',()=>drag=null);$('#network').addEventListener('pointercancel',()=>drag=null);
 $('#export-data').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='influence-atlas-'+data.updatedAt+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};window.addEventListener('hashchange',()=>{readHash();setView(state.view);render();});setView(state.view);render();}
start().catch(error=>{$('#error').hidden=false;$('#error').textContent=error.message+' 로컬 파일을 직접 열었다면 HTTP 서버로 실행해 주세요.';console.error(error);});
